name: Build Starte For Win
on: push
jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install pnpm --location=global
      - run: npm install electron-builder --location=global
      - run: pnpm install
      - run: pnpm packager
      - name: zip Build
        uses: vimtor/action-zip@v1
        with:
            files: build/
            dest: result.zip
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: build/*.exe
